name: shopngoflutter
description: "ShopNGo Flutter Version"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  firebase_auth: ^5.0.0
  fluttertoast: ^8.2.6
  firebase_storage: ^12.1.3
  cached_network_image: ^3.4.0
  cloud_firestore: ^5.2.1
  firebase_database: ^11.0.4

flutter:
  uses-material-design: true
